version: '3'
services:
  bot:
    build: .
    container_name: tanyahukum-bot
    restart: always
    environment: 
      TOKEN: ${TOKEN}
    networks:
      - tanyahukum

networks:  
  tanyahukum:
    driver: bridge